version: "3"

services:
  # prom:
  #   image: "prom/prometheus:v2.34.0"
  #   ports:
  #     - "11001:9090"
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # grafana:
  #   image: "grafana/grafana:8.4.4"
  #   ports:
  #     - "11002:3000"

  # service1:
  #   image: "prom/node-exporter:v1.3.1"
  #   ports:
  #     - "11003:9100"

  influxdb:
    image: "influxdb:2.1.1"
    ports:
      - "11004:8086"

networks:
  default:
    external:
      name: allinone
