services:

  web:
    # image: "trdthg/decision-engine:latest"
    build:
      context: .
      # 请根据情况自选dockerfile
      dockerfile: Dockerfile
      # dockerfile: Dockerfile-skywalking
    ports:
      - "8848:8848"
    depends_on:
      - mysql
      - redis
    restart: always

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "4205:3306"
    logging:
      driver: "none"
    restart: always

  redis:
    image: "redis:alpine"
    ports:
      - "5470:6379"
    logging:
      driver: "none"
