server:
  port: 8848

# true表示生产环境，会关闭swagger
active: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      influx:
        uri: http://influxdb:8086
        bucket: decision-engine
        token: IzKmlQva1QsAxhK5UmlTa7jIP3YpFtMEN37qDJrY-FFMs9Sdob-A2PDXqzhXtmsmeEaaeXEt20XCLO4y8stiUw==
        org: ms

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dev
    username: admin
    password: admin
    # driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
        hbm2ddl:
          auto: update
          # auto: create
  redis:
    host: redis
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 4
      min-idle: 1
    # timeout: 5