server:
  port: 8848

# true表示生产环境，会关闭swagger
active: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      influx:
        uri: http://influxdb:8086
        bucket: decision-engine
        token: IzKmlQva1QsAxhK5UmlTa7jIP3YpFtMEN37qDJrY-FFMs9Sdob-A2PDXqzhXtmsmeEaaeXEt20XCLO4y8stiUw==
        org: ms

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dev?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: admin
    password: admin
  jpa:
    properties:
      # javax:
      #   persistence:
      #     query:
      #       timeout: 1000
      hibernate:
        format_sql: true
#        show_sql: true
        hbm2ddl:
          auto: update
#          auto: create
  redis:
#    database: 0
    host: redis
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 4
      min-idle: 1
#    timeout: 5