server:
  port: 8848

# true表示生产环境，会关闭swagger
active: false

spring:
  datasource:
#    url: jdbc:mysql://tguio.club:4205/dev?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    url: jdbc:mysql://mysql:3306/dev?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    username: admin
    password: admin
  jpa:
    properties:
      # javax:
      #   persistence:
      #     query:
      #       timeout: 1000
      hibernate:
        format_sql: true
#        show_sql: true
        hbm2ddl:
          auto: update
#          auto: create
  redis:
#    database: 0
#    host: tguio.club
    host: redis
#    port: 5470
    port: 6379
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 4
      min-idle: 1
#    timeout: 5