server:
  port: 8848

# true表示生产环境，会关闭swagger
active: false

spring:
  datasource:
    url: jdbc:mysql://tguio.club:4205/dev
    username: root
    password: 2022A22db
  jpa:
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
        hbm2ddl:
          auto: update
          # auto: create
  redis:
    host: tguio.club
    port: 5470
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 4
      min-idle: 1
#    timeout: 5