services:
  redis:
    image: "redis:5.0-alpine"
    ports:
      - "6379:6379"
    logging:
      driver: "none"
    command: [ "redis-server", "--requirepass", "Aa1@0000" ]
  nginx:
    restart: always
    container_name: nginx
    image: nginx
    ports:
      - 8888:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html/:/usr/share/nginx/html/
      - ./nginx/logs/:/var/log/nginx/
